[[docs]]
name = "Websites by name"
weight = 10
identifier = "prologue"
url = "/docs/prologue/"

[[docs]]
name = "Ignore"
weight = 60
identifier = "help"
url = "/docs/help/"

[[main]]
name = "Docs"
url = "/docs/prologue/introduction/"
weight = 10

[[social]]
name = ""
pre = ""
url = ""
post = ""
weight = 20
